version: '3.4'

services:
  sensorpublisher:
    image: sensorpublisher
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ~/.aws:/root/.aws:ro
    privileged: true
    environment: 
      - LOGLEVEL=INFO