# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  RoomDataStack

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  RoomDataTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: RoomData
      AttributeDefinitions: 
        - AttributeName: roomid
          AttributeType: S
        - AttributeName: datetimeunix
          AttributeType: S
      KeySchema: 
        - AttributeName: roomid
          KeyType: HASH
        - AttributeName: datetime
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  # This is an SNS Topic with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
  RoomDataTopic:
    Type: AWS::SNS::Topic
  RoomDataDbARN:  
    Type: AWS::SSM::Parameter
    Properties: 
      Type: String
      Name: /Roomdata/RoomDataTopicArn
      Value:
        Ref: RoomDataTopic
  # This is the Lambda function definition associated with the source code: sns-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SNS topic.
      Runtime: nodejs12.x
      Handler: src/handlers/sns-payload-logger.snsPayloadLoggerHandler
      # This property associates this Lambda function with the SNS topic defined above, so that whenever the topic
      # receives a message, the Lambda function is invoked
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref RoomDataTopic
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
            DYNAMO_DB_NAME: !Ref RoomDataTable
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
    DependsOn: RoomDataDbARN
